server.port: 8083
spring.application.name: vault-transfers
spring.threads.virtual.enabled: true
spring.datasource.url: ${VAULT_JDBC_URL:jdbc:postgresql://localhost:5432/vault}
spring.datasource.username: ${VAULT_DB_USER:vault}
spring.datasource.password: ${VAULT_DB_PASSWORD:vault}
spring.liquibase.change-log: classpath:/db/changelog/master.yaml
spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
